// DIGITAL INPUTS
#define LBUMP 0
#define LFBUMP 1
#define FBUMP 2
#define FRBUMP 3
#define RBUMP 4
#define GRIPBUMP 5
#define LTAPE 8
#define RTAPE 9
#define LINTTAPE 10
#define RINTTAPE 11
//#define LENC1 11
//#define LENC2 12
//#define RENC1 13
//#define RENC2 14

// ANALOG INPUTS
#define IRFRONT 1
#define IRFRONTLEFT 2
#define IRFRONTRIGHT 3
#define IRLEFT 4
#define IRRIGHT 5
#define IRGRIP 6
#define ARMPOS1 7

// MOTOR OUTPUTS
#define LMOTOR 0
#define RMOTOR 1
#define ARMMOTOR1 2
#define ARMMOTOR2 3

// SERVOS
#define ARMSERVO 0
#define GRIPSERVO 1

// ARM SERVO PARAMETERS
#define GRIPSERVMIN 0
#define GRIPSERVMAX 49
#define ARMSERVMIN 0
#define ARMSERVMAX 180
#define ARMSERVOUT 170
#define ARMSERVREST 135
#define ARMSERVNUDGE 10
#define ARMBOX0 120
#define ARMBOX1 150

// ARM POSITION PARAMETERS
//#define ARMREST1 538
//#define ARMREST2 453
//#define ARMLOWIN1 574
//#define ARMLOWIN2 442
//#define ARMLOWOUT1 511
//#define ARMLOWOUT2 298
//#define ARMHIGHIN1 722
//#define ARMHIGHIN2 249
//#define ARMHIGHOUT1 555
//#define ARMHIGHOUT2 83
#define ARMPOSIN 605
#define ARMPOSOUT 497
#define ARMSPEEDPOS 10
#define ARMSPEEDNEG -10
#define ARMTOLERANCE 5

// KNOB INPUTS
#define KNOB1 6
#define KNOB2 7

// MAP INDICES
#define LEFT 0
#define RIGHT 1
#define STRAIGHT 2

// BOOLEANS
#define TRUE 1
#define FALSE 0
