// DIGITAL INPUTS
#define LTAPE 0
#define RTAPE 1
#define LINTTAPE 2
#define RINTTAPE 3
#define LGRIPBUMP 4
#define RGRIPBUMP 5
#define BGRIPBUMP 6
#define FBUMP 7
#define LBUMP 8
#define RBUMP 9
#define BOXMOTOR 10
//#define LENC1 11
//#define LENC2 12
//#define RENC1 13
//#define RENC2 14

// ANALOG INPUTS
#define IRFRONT 0
#define IRFRONTLEFT 1
#define IRFRONTRIGHT 2
#define IRLEFT 3
#define IRRIGHT 4
#define IRGRIP 5
#define ARMPOS1 6
#define ARMPOS2 7

// MOTOR OUTPUTS
#define LMOTOR 0
#define RMOTOR 1
#define ARMMOTOR1 2
#define ARMMOTOR2 3

// SERVOS
#define ARMSERVO 0
#define GRIPSERVO 1

// ARM SERVO PARAMETERS
#define GRIPSERVMIN 70
#define GRIPSERVMAX 120
#define ARMSERVMIN 0
#define ARMSERVMAX 180
#define ARMSERVREST 135
#define ARMBOX0 120
#define ARMBOX1 150

// ARM POSITION PARAMETERS
#define ARMREST1 538
#define ARMREST2 453
#define ARMLOWIN1 574
#define ARMLOWIN2 442
#define ARMLOWOUT1 511
#define ARMLOWOUT2 298
#define ARMHIGHIN1 722
#define ARMHIGHIN2 249
#define ARMHIGHOUT1 555
#define ARMHIGHOUT2 83
#define ARMSPEEDPOS 10
#define ARMSPEEDNEG -10
#define ARMTOLERANCE 5

// KNOB INPUTS
#define KNOB1 6
#define KNOB2 7

// MAP INDICES
#define LEFT 0
#define RIGHT 1
#define STRAIGHT 2

// BOOLEANS
#define TRUE 1
#define FALSE 0
